### ISSUE TITLE
Incorrectly reports valid characters as "invalid identifier"

### ISSUE THREAD

**Issue by chrisvfritz** [AtomLinter/linter-lsc#14]
`Ω` and other [characters that are valid in JavaScript variable names](http://stackoverflow.com/questions/1661197/what-characters-are-valid-for-javascript-variable-names#answer-9337047) are incorrectly reported as invalid.

**Comment by steelbrain** [comment]
Does the reporting differ from the command line lsc executable? If not, you might wanna open a bug in their repo :)

**Comment by chrisvfritz** [comment]
Yes, it does differ. lsc for `LiveScript version 1.4.0` seems to have no problem parsing the character. For example, `lsc -e "Ω = 'blah'"` returns no errors and the file I'm working in is correctly compiled by Webpack's livescript-loader.

**Comment by Arcanemagus** [comment]
Interestingly on Windows both in the CLI and through the Node.js API that character works, however on Linux that character works when run through the CLI, but the Node.js API fails on that character. You'll have to file an issue with `livescript` as to why it validates differently on the Node.js API on Linux.
