### ISSUE TITLE
Does NOT work in windows system

### ISSUE THREAD

**Issue by ginus** [AtomLinter/linter-lsc#2]
The default lsc excuteable path is c:\Users\Administrator\.atom\packages\linter-lsc\node_modules\LiveScript\bin\lsc. and console log shows this 'is node executable: false'.

**Comment by johngeorgewright** [comment]
As I don't have access to a Windows machine where I am, could you tell me if you can execute that file from the shell? If there's another way of running LiveScript in Windows, you can configure the linter to use that instead by adding a `lscExecutablePath` in your config file.

**Comment by ginus** [comment]
could you tell me if you can execute that file from the shell?
yes, I can. like "lsc -c -b gulpfile.ls"

**Comment by johngeorgewright** [comment]
Just so I'm clear... the command you've written there `lsc ...` aliases to `c:\Users\Administrator.atom\packages\linter-lsc\node_modules\LiveScript\bin\lsc`?

**Comment by ginus** [comment]
No, lsc is global. the default exePath is a js that must run by node.exe but debug log shows "is node executable: false". I think if it to be true, then it will works.

**Comment by johngeorgewright** [comment]
It had also stopped working on my system since an update too. Fixed.

**Comment by ginus** [comment]
good job! thx!
