### ISSUE TITLE
lsc renturned stderr field at 'bad.ls',NOT THE RESEAN

### ISSUE THREAD

**Issue by ginus** [AtomLinter/linter-lsc#3]
linter-lsc still not works well, now it executes but not the error information returned

**Comment by johngeorgewright** [comment]
Do you mean that you're just not seeing the error message in the status bar? Or that you're seeing an incorrect message? It works ok for me, so there must be a different output on windows. Do you fancy trying a pull request?

**Comment by ginus** [comment]
I am seeing "stderr field at 'bad.ls'", and nothing in status bar
